version: '3.9'

services:
  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_config/configs:/etc/nginx/conf.d:ro
      - static-content:/data/static/
    depends_on:
      - web
    ports:
      - "80:80"

  web:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: ${REQUIREMENTS_FILE}
    volumes:
    - static-content:${STATIC_ROOT}
    env_file:
      - .env
      - .db_env
    depends_on:
      - db
      - redis
    restart: on-failure

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/:z
    env_file:
      - .db_env
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2
    restart: always


volumes:
  postgres_data:
  static-content:
networks:
  default:
    name: meduza-project-net