# Generated by Django 4.0.2 on 2022-02-02 13:38

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, verbose_name='заголовок')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='семантический URL')),
                ('body', models.TextField(verbose_name='контент')),
                ('published', models.DateField(verbose_name='дата публикации')),
                ('is_archived', models.BooleanField(default=False, verbose_name='в архиве?')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
