# Generated by Django 4.0.2 on 2022-02-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-published',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
