#!/bin/bash

set -e

psql -U postgres -c "CREATE DATABASE $POSTGRES_D;"
psql -U postgres -c "CREATE USER $POSTGRES_CREATE_USER WITH PASSWORD '$POSTGRES_CREATE_USER_PASSWORD';"
psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_D TO $POSTGRES_CREATE_USER;"